<?php

namespace app\controllers;

use app\models\Besoin;
use app\models\Categorie;
use app\models\Ville;
use app\services\BesoinService;
use Flight;

class BesoinController
{
    protected BesoinService $besoinService;

    public function __construct()
    {
        $this->besoinService = new BesoinService();
    }

    /**
     * Show the form to create a new need
     */
    public function create()
    {
        try {
            // Get reference data for the form
            $categorieModel = new Categorie();
            $villeModel = new Ville();

            $categories = $categorieModel->getAll();
            $villes = $villeModel->getAllWithRegion();

            Flight::render('BesoinCreate', [
                'categories' => $categories,
                'villes' => $villes,
                'title' => 'Nouveau Besoin'
            ]);
        } catch (\Throwable $e) {
            error_log('BesoinController create error: ' . $e->getMessage());
            Flight::halt(500, 'Erreur lors du chargement du formulaire');
        }
    }

    /**
     * Process the creation of a new need
     */
    public function store()
    {
        try {
            $data = Flight::request()->data;

            // Validate required fields
            $required_fields = ['ville_id', 'categorie_id', 'description', 'quantite'];
            foreach ($required_fields as $field) {
                if (empty($data->$field)) {
                    Flight::halt(400, "Le champ $field est requis");
                }
            }

            // Validate numeric fields
            if (!is_numeric($data->quantite) || $data->quantite <= 0) {
                Flight::halt(400, 'La quantité doit être un nombre positif');
            }

            if (!empty($data->prix_unitaire) && (!is_numeric($data->prix_unitaire) || $data->prix_unitaire < 0)) {
                Flight::halt(400, 'Le prix unitaire doit être un nombre positif');
            }



            $besoinModel = new Besoin();

            // Prepare data for insertion
            // Note: 'created_at' and 'updated_at' are auto-generated by database
            $insertData = [
                'ville_id' => (int) $data->ville_id,
                'categorie_id' => (int) $data->categorie_id,
                'status_id' => 1, // Default to first status
                'description' => trim($data->description),
                'quantite' => (int) $data->quantite,
                'prix_unitaire' => !empty($data->prix_unitaire) ? (float) $data->prix_unitaire : 0.00,
                'priorite' => 'normale', // Default priority
                'date_besoin' => !empty($data->date_besoin) ? $data->date_besoin : date('Y-m-d H:i:s')
            ];

            $result = $besoinModel->create($insertData);

            if ($result) {
                // Redirect to the needs list or dashboard with success message
                $baseUrl = Flight::get('flight.base_url');
                header('Location: ' . $baseUrl . '/besoin?message=success');
                exit;
            } else {
                Flight::halt(500, 'Erreur lors de l\'enregistrement du besoin');
            }

        } catch (\Throwable $e) {
            error_log('BesoinController store error: ' . $e->getMessage());
            Flight::halt(500, 'Erreur lors de la création du besoin');
        }
    }

    /**
     * List all needs
     */
    public function index()
    {
        try {
            $besoins = $this->besoinService->getAllWithDetails();

            Flight::render('BesoinIndex', [
                'besoins' => $besoins,
                'title' => 'Liste des Besoins'
            ]);
        } catch (\Throwable $e) {
            error_log('BesoinController index error: ' . $e->getMessage());
            Flight::halt(500, 'Erreur lors du chargement des besoins');
        }
    }

    /**
     * Show a specific need
     */
    public function show($id)
    {
        try {
            $besoinModel = new Besoin();
            $besoin = $besoinModel->getByIdWithDetails($id);

            if (empty($besoin)) {
                Flight::halt(404, 'Besoin introuvable');
            }

            Flight::render('BesoinShow', [
                'besoin' => $besoin,
                'title' => 'Détails du Besoin'
            ]);
        } catch (\Throwable $e) {
            error_log('BesoinController show error: ' . $e->getMessage());
            Flight::halt(500, 'Erreur lors du chargement du besoin');
        }
    }
}